services:
  db:
    image: postgis/postgis:15-3.3
    container_name: catastro_db_beta
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=catastro_dev_password
      - POSTGRES_DB=avalix_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_v2:/var/lib/postgresql/data
      # Ejecuta todos los scripts SQL al crear un volumen nuevo.
      - ./db_init:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata_v2:
